#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"/..
ROOT=`pwd`

docker run -ti --rm \
    -v $ROOT:/src \
    --link mp-database:database \
    --link mp-webdriver:webdriver \
    --link mp-front:web \
    -w /src \
    myproject/api \
    vendor/bin/behat "$@" # pass arguments

